### ISSUE TITLE
recime-cli run gives a panic error

### ISSUE THREAD

**Issue by benhalverson** [Recime/recime-cli#2]
https://github.com/Recime/recime-template/archive/1.0.1.zip does not exist 
```
Downloading https://github.com/Recime/recime-template/archive/1.0.1.zip
Error while creating /Users/benhalverson/recime-app/recime-1.0.1.zip - open /Users/benhalverson/recime-app/recime-1.0.1.zip: no such file or directory
panic: open /Users/benhalverson/recime-app/recime-1.0.1.zip: no such file or directory

goroutine 1 [running]:
panic(0x31c2e0, 0xc420013890)
	/usr/local/Cellar/go/1.7.3/libexec/src/runtime/panic.go:500 +0x1a1
github.com/Recime/recime-cli/cmd.check(0x4ef800, 0xc420013890)
	/private/tmp/recime-cli-20161201-27896-93cjms/recime-cli-1.0.6/src/github.com/Recime/recime-cli/cmd/init.go:122 +0x5c
github.com/Recime/recime-cli/cmd.Run(0xc4200137a0)
	/private/tmp/recime-cli-20161201-27896-93cjms/recime-cli-1.0.6/src/github.com/Recime/recime-cli/cmd/run.go:65 +0x44c
main.main.func7(0xc42009fb00, 0x533f98, 0x0, 0x0)
	/private/tmp/recime-cli-20161201-27896-93cjms/recime-cli-1.0.6/main.go:108 +0x185
github.com/spf13/cobra.(*Command).execute(0xc42009fb00, 0x533f98, 0x0, 0x0, 0xc42009fb00, 0x533f98)
	/private/tmp/recime-cli-20161201-27896-93cjms/recime-cli-1.0.6/src/github.com/spf13/cobra/command.go:636 +0x443
github.com/spf13/cobra.(*Command).ExecuteC(0xc42009fd40, 0xc420053e70, 0xc420074501, 0xc42009fd40)
	/private/tmp/recime-cli-20161201-27896-93cjms/recime-cli-1.0.6/src/github.com/spf13/cobra/command.go:722 +0x367
github.com/spf13/cobra.(*Command).Execute(0xc42009fd40, 0xc420053e68, 0x1)
	/private/tmp/recime-cli-20161201-27896-93cjms/recime-cli-1.0.6/src/github.com/spf13/cobra/command.go:681 +0x2b
main.main()
	/private/tmp/recime-cli-20161201-27896-93cjms/recime-cli-1.0.6/main.go:130 +0x76a

 ```

**Comment by mehfuzh** [comment]
Hi Ben,
Thanks for Reporting it. Right now you can make it work by manually creating "recime-app" directory under /Users/benhalverson/ . We are working on a version later this evening that will resolve the issue.


Thanks
M
